export const LOAD_WOMEN_SUCCESS = 'LOAD_WOMEN_SUCCESS';
export const UPDATE_WOMAN_SUCCESS = 'UPDATE_WOMAN_SUCCESS';
export const CREATE_WOMAN_SUCCESS = 'CREATE_WOMAN_SUCCESS';
export const DELETE_WOMAN_SUCCESS = 'DELETE_WOMAN_SUCCESS';